// Generated from `Tool Categories/garage_tool_categories.csv` — the source of
// truth for the taxonomy. Regenerate rather than hand-editing.
//
// Both levels matter. A listing stores its parent `category` and its
// `subcategory` in separate columns (0026_listing_fields.sql), and both feed
// the search vector, so "Automotive" and "Brake & suspension service" each
// find the same tool. The picker searches subcategory text as well as
// category names — a flat list of 37 top-level categories was far too
// coarse to find anything in.

export const CATEGORY_TREE = [
  {
    category: "Air & Compressed Air",
    subcategories: [
      "Air compressors",
      "Air hoses & reels",
      "Fittings, couplers & manifolds",
      "Regulators, filters & dryers",
      "Blow guns & air nozzles",
      "Tire inflators & gauges",
      "Air tool oil & lubricators",
      "Piping & distribution",
    ],
  },
  {
    category: "Automotive",
    subcategories: [
      "Lifting & support (jacks, stands, ramps)",
      "Diagnostics & scan tools",
      "Fluid service (oil, coolant, transmission, brake)",
      "Brake & suspension service",
      "Tire & wheel service",
      "Engine & drivetrain service",
      "Battery & charging",
      "Body repair",
      "Vehicle detailing",
    ],
  },
  {
    category: "Bicycle",
    subcategories: [
      "Drivetrain tools (chain, cassette, bottom bracket)",
      "Wheel & tire tools",
      "Brake & hydraulic tools",
      "Repair stands & workholding",
      "Components & spare parts",
      "Cleaning & lubrication",
      "Riding gear & apparel",
      "Racks, transport & storage",
    ],
  },
  {
    category: "Chemicals & Consumables",
    subcategories: [
      "Wood glue",
      "Cyanoacrylate & instant adhesives",
      "Two-part epoxies",
      "Construction & panel adhesive",
      "Contact cement & spray adhesive",
      "Hot melt glue & sticks",
      "Sealants & caulk",
      "Threadlockers & retaining compounds",
      "Lubricants & penetrants",
      "Greases & anti-seize",
      "Solvents & degreasers",
      "Rust prevention & treatment",
      "Shop cleaners & soaps",
      "Sandpaper & sheets",
      "Sanding discs & belts",
      "Flap discs & grinding wheels",
      "Cutoff wheels",
      "Wire wheels & brushes",
      "Polishing & buffing compounds",
      "Duct, masking & electrical tape",
      "Double-sided & mounting tape",
      "Specialty films & wraps",
      "Shop rags, towels & disposables",
      "Filters & replacement consumables",
    ],
  },
  {
    category: "Cleaning",
    subcategories: [
      "Shop vacuums & dust extraction",
      "Air filtration",
      "Pressure washers",
      "Floor care (brooms, mops, scrubbers, squeegees)",
      "Parts washers & solvent tanks",
      "Brushes, rags & wipes",
      "Waste & recycling containers",
    ],
  },
  {
    category: "Craft",
    subcategories: [
      "Sewing & textiles",
      "Leatherwork",
      "Jewelry & small metalwork",
      "Figurine sculpting & painting",
      "Model building & miniatures",
      "Prototyping & desktop 3D printing",
      "Resin, casting & molds",
      "Paper, vinyl & die cutting",
      "Pottery & clay",
      "Art & drafting supplies",
      "Brewing & fermentation",
      "Winemaking & pressing",
      "Bottling, kegging & capping",
      "Sanitizing & cleaning supplies",
    ],
  },
  {
    category: "Electrical",
    subcategories: [
      "Wire strippers & crimpers",
      "Conduit benders & cutters",
      "Fish tape & wire pulling",
      "Terminals, connectors & lugs",
      "Wire, cable & raceway",
      "Boxes, outlets & switches",
      "Breakers & panel hardware",
      "Extension cords & reels",
    ],
  },
  {
    category: "Electronic",
    subcategories: [
      "Soldering & rework",
      "Desoldering & hot air",
      "Prototyping (breadboards, perfboard)",
      "PCB fabrication & assembly",
      "Components & modules",
      "Microcontrollers & single-board computers",
      "ESD protection & handling",
      "Hookup wire & headers",
      "Enclosures & panel hardware",
    ],
  },
  {
    category: "Fasteners",
    subcategories: [
      "Screws (wood, machine, sheet metal, deck)",
      "Bolts, nuts & washers",
      "Nails, brads & staples",
      "Anchors & concrete fasteners",
      "Rivets & rivet nuts",
      "Pins, clips & retaining rings",
      "Threaded rod & inserts",
      "Assortment kits & organizers",
    ],
  },
  {
    category: "Fishing",
    subcategories: [
      "Rods & reels",
      "Line, leader & terminal tackle",
      "Lures, baits & flies",
      "Nets, gaffs & landing gear",
      "Fish finders & marine electronics",
      "Rod building & lure making",
      "Waders, apparel & PFDs",
      "Tackle boxes & rod storage",
    ],
  },
  {
    category: "Fitness",
    subcategories: [
      "Cardio equipment",
      "Free weights & barbells",
      "Racks, benches & cages",
      "Machines & cable systems",
      "Bands, ropes & bodyweight gear",
      "Recovery & mobility",
      "Flooring & mats",
      "Equipment storage & racks",
    ],
  },
  {
    category: "Garage Door",
    subcategories: [
      "Openers & drives",
      "Remotes, keypads & receivers",
      "Torsion & extension springs",
      "Cables, drums & bearings",
      "Tracks, rollers & hinges",
      "Panels & sections",
      "Weather seals & thresholds",
      "Safety sensors & reversing",
      "Locks & security hardware",
      "Insulation kits",
      "Winding bars & install tools",
    ],
  },
  {
    category: "Hammers",
    subcategories: [
      "Claw & framing",
      "Ball-peen & machinist",
      "Sledge & drilling",
      "Mallets (rubber, dead blow, wood, brass)",
      "Masonry & brick",
      "Body & fender (with dollies)",
      "Specialty (tack, drywall, roofing)",
      "Handles & replacement parts",
    ],
  },
  {
    category: "Ladders",
    subcategories: [
      "Step ladders",
      "Extension ladders",
      "Multi-position & articulating",
      "Platform & podium",
      "Step stools",
      "Attic & loft",
      "Scaffolding & work platforms",
      "Accessories (stabilizers, levelers, standoffs)",
    ],
  },
  {
    category: "Lawn & Garden",
    subcategories: [
      "Mowers",
      "Trimmers & edgers",
      "Pruning & cutting tools",
      "Digging & soil tools",
      "Tillers & cultivators",
      "Watering & irrigation",
      "Spreaders & sprayers",
      "Leaf blowers & rakes",
      "Seeds, soil & amendments",
      "Weed & pest control",
    ],
  },
  {
    category: "Lighting",
    subcategories: [
      "Shop & ceiling fixtures",
      "Work & task lights",
      "Portable & rechargeable lights",
      "Headlamps & flashlights",
      "Inspection & underhood lights",
      "String & festoon lighting",
      "Outdoor & landscape lighting",
      "Security & motion lighting",
      "Emergency & exit lighting",
      "Bulbs & lamps",
      "Ballasts, drivers & dimmers",
      "Light stands & tripods",
    ],
  },
  {
    category: "Livestock & Pet",
    subcategories: [
      "Feeders & waterers",
      "Fencing & containment",
      "Grooming & clipping",
      "Health, vet & first aid",
      "Handling & restraint",
      "Housing, bedding & kennels",
      "Waste management",
      "Leashes, collars & training",
      "Feed & bedding storage",
    ],
  },
  {
    category: "Machining",
    subcategories: [
      "Lathes",
      "Milling machines",
      "Drill presses",
      "Metal cutting machines (bandsaw, cold saw)",
      "Surface & tool grinding",
      "Workholding (vises, chucks, collets, fixtures)",
      "Threading (taps, dies, thread repair)",
      "Layout & marking (surface plates, scribes, height gauges)",
      "CNC controls & tooling",
    ],
  },
  {
    category: "Material Handling",
    subcategories: [
      "Hand trucks & dollies",
      "Carts & platform trucks",
      "Engine hoists & shop cranes",
      "Chain hoists & lever hoists",
      "Winches & come-alongs",
      "Pallet jacks & lift tables",
      "Pry bars & rollers",
      "Casters & wheels",
      "Load levelers & positioning gear",
      "Pulleys & blocks",
    ],
  },
  {
    category: "Materials",
    subcategories: [
      "Lumber & dimensional wood",
      "Sheet goods (plywood, MDF, OSB)",
      "Hardwood & specialty wood",
      "Metal bar & rod",
      "Metal tube & pipe stock",
      "Metal sheet & plate",
      "Plastics & acrylics",
      "Composites & foam",
      "Rubber & gasket stock",
      "Glass & glazing",
      "Concrete, mortar & aggregate",
      "Brick, block & stone",
      "Drywall & plaster",
      "Roofing & siding",
      "Insulation & weatherproofing",
      "Flooring & underlayment",
      "Fencing & decking",
    ],
  },
  {
    category: "Measurement",
    subcategories: [
      "Tape measures & rules",
      "Squares & angle finders",
      "Levels (spirit, torpedo, laser)",
      "Calipers & micrometers",
      "Dial indicators & gauge blocks",
      "Marking & scribing tools",
      "Chalk lines & layout lasers",
      "Multimeters & electrical testers",
      "Oscilloscopes & signal tools",
      "Temperature, pressure & moisture meters",
      "Scales & balances",
      "Stud & cable finders",
    ],
  },
  {
    category: "Outdoor Living",
    subcategories: [
      "Grills & smokers",
      "Fire pits & patio heaters",
      "Patio furniture & care",
      "Awnings, canopies & shade",
      "Pool & spa maintenance",
      "Deck & fence maintenance",
      "Snow & ice removal",
    ],
  },
  {
    category: "Paint & Finishing",
    subcategories: [
      "Paints, stains & clear coats",
      "Brushes & rollers",
      "Spray guns (HVLP, conventional)",
      "Airless & airbrush systems",
      "Surface prep & strippers",
      "Masking & drop cloths",
      "Mixing, straining & storage",
      "Spray booths & ventilation",
      "Curing lamps & drying racks",
      "Buffing & polishing",
    ],
  },
  {
    category: "Pliers & Clamps",
    subcategories: [
      "Slip-joint & tongue-and-groove",
      "Needle-nose & long-reach",
      "Lineman's & combination",
      "Locking pliers",
      "Diagonal & end cutters",
      "Snap ring & specialty pliers",
      "Tin snips & aviation snips",
      "Bolt cutters",
      "Cable & wire rope cutters",
      "Bar & pipe clamps",
      "Spring, C & F clamps",
      "Band, strap & corner clamps",
    ],
  },
  {
    category: "Plumbing",
    subcategories: [
      "Pipe cutters & threaders",
      "Tubing benders & flaring tools",
      "PEX & press tools",
      "Drain augers & snakes",
      "Sweat & soldering tools",
      "Pipe wrenches & grips",
      "Pipe, fittings & valves",
      "Fixtures & supply lines",
      "Pumps & water treatment",
      "Thread sealant & tape",
    ],
  },
  {
    category: "Power Tools",
    subcategories: [
      "Drills & impact drivers",
      "Hammer drills & rotary hammers",
      "Circular & track saws",
      "Miter & table saws",
      "Reciprocating, jig & band saws",
      "Grinders",
      "Sanders",
      "Routers & planers",
      "Nailers & staplers",
      "Rotary & oscillating multi-tools",
      "Pneumatic tools",
      "Generators & power supply",
      "Heat guns & torches",
      "Batteries, chargers & cordless platforms",
    ],
  },
  {
    category: "Rope & Cable",
    subcategories: [
      "Rope & cordage",
      "Chain & chain hardware",
      "Wire rope & cable",
      "Webbing, straps & tie-downs",
      "Bungee & elastic cord",
      "Rigging hardware (shackles, thimbles, clamps)",
      "Knot, splicing & swaging tools",
      "Cable management & ties",
    ],
  },
  {
    category: "Safety & PPE",
    subcategories: [
      "Eye & face protection",
      "Hearing protection",
      "Respiratory protection",
      "Hand & arm protection",
      "Head & foot protection",
      "Protective clothing & hi-vis",
      "Fall protection & harnesses",
      "Welding helmets & leathers",
      "Fire extinguishers & suppression",
      "First aid & eyewash",
      "Lockout/tagout",
      "Signage, barriers & marking",
      "Gas detection & monitors",
      "Spill control & absorbents",
    ],
  },
  {
    category: "Saws & Blades",
    subcategories: [
      "Hand saws (panel, rip, crosscut)",
      "Back saws & joinery saws",
      "Coping, fret & hack saws",
      "Pruning & bow saws",
      "Utility knives & box cutters",
      "Hobby, craft & detail knives",
      "Fixed & folding shop knives",
      "Circular & miter saw blades",
      "Reciprocating, jig & band saw blades",
      "Replacement utility & hobby blades",
      "Drill, spade & hole saw bits",
      "Router, planer & shaper cutters",
      "Sharpening & blade maintenance",
    ],
  },
  {
    category: "Screwdrivers",
    subcategories: [
      "Slotted / flat",
      "Phillips",
      "Torx & security",
      "Hex / Allen",
      "Square (Robertson)",
      "Precision & jeweler's",
      "Insulated / electrician",
      "Ratcheting & multi-bit",
      "Nut drivers",
      "Offset, stubby & right-angle",
      "Bit sets & bit holders",
    ],
  },
  {
    category: "Shelves & Cabinets",
    subcategories: [
      "Freestanding shelving units",
      "Wall-mounted shelving",
      "Heavy-duty racking & pallet rack",
      "Overhead & ceiling racks",
      "Wall systems (pegboard, slatwall, French cleat)",
      "Base & wall cabinets",
      "Lockers & storage cabinets",
      "Countertops & work surfaces",
      "Drawer slides & cabinet hardware",
      "Brackets, standards & supports",
      "Hooks & hangers",
    ],
  },
  {
    category: "Sporting",
    subcategories: [
      "Hunting & shooting",
      "Archery",
      "Camping & backpacking",
      "Water sports & paddling",
      "Winter sports",
      "Team & field sports",
      "Optics (binoculars, scopes, rangefinders)",
      "Game processing",
      "Gear storage & transport",
    ],
  },
  {
    category: "Storage",
    subcategories: [
      "Tool boxes & chests",
      "Rolling tool cabinets & carts",
      "Small-parts bins & organizers",
      "Tool bags, pouches & belts",
      "Totes & storage bins",
      "Drawer liners & foam inserts",
      "Safes & locking storage",
      "Seasonal & long-term storage",
    ],
  },
  {
    category: "Tables & Benches",
    subcategories: [
      "Workbenches",
      "Assembly & outfeed tables",
      "Miter & router tables",
      "Saw horses & portable supports",
      "Tool stands & mobile bases",
      "Bench vises",
      "Bench dogs, holdfasts & accessories",
      "Bench tops & hardware",
    ],
  },
  {
    category: "Welding & Metal Fab",
    subcategories: [
      "MIG welders",
      "TIG welders",
      "Stick & multi-process welders",
      "Plasma cutters",
      "Oxy-fuel torches & gas",
      "Spot & stud welding",
      "Brazing & metal soldering",
      "Sheet metal brakes & rollers",
      "Shears & nibblers",
      "Punches, dimple dies & English wheels",
      "Welding tables & positioners",
      "Welding clamps & magnets",
      "Fume extraction & screens",
      "Welding consumables (rod, wire, gas)",
    ],
  },
  {
    category: "Wood & Carpentry",
    subcategories: [
      "Chisels & carving tools",
      "Hand planes & spokeshaves",
      "Scrapers, rasps & files",
      "Joinery systems (dowel, pocket hole, biscuit, domino)",
      "Wood turning & lathe tools",
      "Wood carving & whittling",
      "Wood burning & pyrography",
      "Furniture making & cabinetmaking",
      "Veneering & inlay",
      "Doweling, plugs & joinery hardware",
      "Sharpening stones, jigs & strops",
    ],
  },
  {
    category: "Wrenches",
    subcategories: [
      "Combination, open-end & box-end",
      "Adjustable",
      "Sockets & ratchets",
      "Extensions, adapters & universal joints",
      "Breaker bars & speed handles",
      "Impact sockets & accessories",
      "Torque wrenches & multipliers",
      "Hex & Torx keys",
      "Line, flare nut & specialty",
      "Spanner & pin wrenches",
      "Strap & filter wrenches",
    ],
  },
];

/** Just the top-level names, in source order. */
export const TOOL_CATEGORIES = CATEGORY_TREE.map((c) => c.category);

/**
 * Every pickable option, flattened for searching: one entry per subcategory,
 * plus one bare entry per category for someone who only wants to say
 * "Automotive", plus a final "Other" catch-all.
 *
 * `label` is what the picker matches against and shows, so typing either
 * half of "Automotive — Brake" narrows to the same row.
 */
export const CATEGORY_OPTIONS = [
  ...CATEGORY_TREE.flatMap((c) => [
    { category: c.category, subcategory: "", label: c.category },
    ...c.subcategories.map((s) => ({
      category: c.category,
      subcategory: s,
      label: `${c.category} — ${s}`,
    })),
  ]),
  { category: "Other", subcategory: "", label: "Other" },
];

/** How a stored (category, subcategory) pair reads back in the UI. */
export function categoryLabel(category, subcategory) {
  if (!category) return "";
  return subcategory ? `${category} — ${subcategory}` : category;
}
