-- Counting the people who never sign in (audit RLS-3).
--
-- Search and a tool's page are public, and they are the top of the funnel:
-- somebody arrives, looks for a ladder, reads one listing, and either makes an
-- account or leaves. Until now the entire left-hand half of that was
-- invisible. `events_insert_own` is `with check (profile_id = auth.uid())`,
-- which is NULL for anon, so every anonymous action was refused by the
-- database and `logEvent` did not even try. The internal events table is the
-- whole analytics strategy, so "how many people bounce off the public pages"
-- had no answer at all -- including the one that matters, what they searched
-- for and found nothing.
--
-- The obvious fix -- widen the insert policy to anon with `profile_id is null`
-- -- was rejected. It hands every visitor on the internet an unthrottled write
-- endpoint into a table the admin console reads, with a free-form `metadata`
-- jsonb column, which is a storage bucket with extra steps. So the table keeps
-- its closed policy and anon gets one function instead:
--
--   * the event type must be one of two. Not a whitelist for tidiness -- an
--     unlisted type is the shape a spammer would use to write whatever they
--     liked into the dashboard's activity chart.
--
--   * `metadata` is *built here* from typed arguments, never accepted as a
--     blob, and the search text is clipped. A caller cannot put anything in
--     that row that this function did not decide to put there.
--
--   * `profile_id` is `auth.uid()`, never an argument. The function is
--     granted to `authenticated` as well as `anon` for a reason that is not
--     generosity: a returning visitor's session is restored asynchronously, so
--     the first render of a public page genuinely does not know who they are
--     yet. Letting the database answer that question instead of the client
--     means the row is attributed correctly whenever the JWT has arrived, and
--     there is no argument to forge when it has not.
--
--   * anonymous rows are capped per minute, globally. A per-visitor limit
--     would be better and is not available: there is nothing to key it on but
--     an IP address, which would mean storing a pseudonymous identifier for
--     somebody who has not signed in, for the sake of a Low-severity finding.
--     A global cap can be starved by one determined spammer -- the measurement
--     degrades, the table does not grow without bound, and nothing else in the
--     app depends on these rows. That is the trade, taken deliberately.
--
-- The session id in `metadata` is generated by the browser per *tab session*
-- (sessionStorage, not localStorage) and is forgeable. It is not a security
-- control and nothing may treat it as one; it exists so that three page views
-- by one person do not read as three people, which is the only way "visitors"
-- and "searches" mean different things.
--
-- Safe to paste and re-run from the top.

-- ============================================================
-- 1. The index the throttle reads
-- ============================================================
-- Partial: the cap only ever counts anonymous rows, and those are a small
-- minority of the table. `events_created_idx` would work and would make the
-- check scan every signed-in event in the window to discard it.
create index if not exists events_anon_recent_idx
  on events (created_at)
  where profile_id is null;

-- ============================================================
-- 2. The one write path
-- ============================================================
create or replace function log_visitor_event(
  p_event_type text,
  p_session    uuid,
  p_tool_id    uuid default null,
  p_query      text default null,
  p_results    integer default null,
  p_near       boolean default null
)
returns void
language plpgsql
security definer
set search_path = public
as $fn$
declare
  -- Both are logged from pages a signed-out visitor can reach. Nothing else
  -- is: every other event in `EVENTS` happens behind RequireAuth, where the
  -- ordinary insert already works and is attributed.
  c_allowed  constant text[] := array['search_performed', 'tool_viewed'];
  -- Roughly five a second, which no honest visitor approaches and which bounds
  -- the table at a size the console can still read back.
  c_cap      constant integer := 300;
  v_me       uuid := auth.uid();
begin
  if not (p_event_type = any (c_allowed)) then
    raise exception 'log_visitor_event does not accept %', p_event_type;
  end if;
  if p_session is null then
    raise exception 'A session id is required, or the counts cannot tell people apart';
  end if;

  if v_me is null then
    -- `offset` stops at the cap rather than counting the whole window, so the
    -- cost of being under attack does not rise with the size of the attack.
    perform 1 from events
    where profile_id is null
      and created_at > now() - interval '1 minute'
    offset c_cap limit 1;
    if found then
      return;
    end if;
  end if;

  insert into events (profile_id, event_type, metadata)
  values (
    v_me,
    p_event_type,
    jsonb_strip_nulls(jsonb_build_object(
      'session', p_session,
      'tool_id', p_tool_id,
      'query',   nullif(left(btrim(p_query), 100), ''),
      'results', greatest(0, least(p_results, 100000)),
      'near',    p_near
    ))
  );
end;
$fn$;

-- 0046 made `anon` opt-in rather than default, so this GRANT is the whole
-- reason the function is reachable at all -- and `revoke ... from public`
-- first, because that is the shape that actually removes a privilege.
revoke execute on function log_visitor_event(text, uuid, uuid, text, integer, boolean) from public;
grant execute on function log_visitor_event(text, uuid, uuid, text, integer, boolean) to anon, authenticated;

-- ============================================================
-- 3. Telling the two populations apart in the console
-- ============================================================
-- `searches_30d` counted every `search_performed` row and did not need to say
-- whose, because they were all signed in. From today it is a mixed number, and
-- a tile that silently changes meaning is worse than one that never existed --
-- somebody reads the jump as growth. So the anonymous half is broken out, and
-- distinct sessions come with it: searches measure activity, sessions measure
-- people, and the ratio between them is the only interesting thing here.
--
-- A dropped-and-recreated function, not `create or replace`: the return type
-- is changing, which `replace` refuses. It takes no arguments, so there is no
-- second overload to leave behind.
drop function if exists admin_overview();

create function admin_overview()
returns table (
  accounts bigint,
  accounts_active bigint,
  accounts_complete bigint,
  accounts_private bigint,
  signups_7d bigint,
  signups_30d bigint,
  tools bigint,
  tools_paused bigint,
  tools_on_loan bigint,
  groups_total bigint,
  memberships_approved bigint,
  requests_pending bigint,
  requests_approved bigint,
  requests_completed bigint,
  requests_denied bigint,
  reports_open bigint,
  feedback_total bigint,
  searches_30d bigint,
  searches_30d_anon bigint,
  visitors_30d_anon bigint
)
language plpgsql
stable
security definer
set search_path = public
as $fn$
begin
  if not is_platform_admin_now() then
    raise exception 'Not permitted';
  end if;

  return query
  select
    (select count(*) from profiles),
    (select count(*) from profiles where deleted_at is null),
    (select count(*) from profiles where profile_complete and deleted_at is null),
    (select count(*) from profiles where identity_private and deleted_at is null),
    (select count(*) from profiles where created_at > now() - interval '7 days'),
    (select count(*) from profiles where created_at > now() - interval '30 days'),
    (select count(*) from tools),
    (select count(*) from tools where paused),
    (select count(*) from tools where status = 'borrowed'),
    (select count(*) from groups),
    (select count(*) from group_memberships where status = 'approved'),
    (select count(*) from borrow_requests where status = 'pending'),
    (select count(*) from borrow_requests where status = 'approved'),
    (select count(*) from borrow_requests where status = 'completed'),
    (select count(*) from borrow_requests where status = 'denied'),
    (select count(*) from user_reports where resolved_at is null),
    (select count(*) from feedback),
    (select count(*) from events where event_type = 'search_performed'
       and created_at > now() - interval '30 days'),
    (select count(*) from events where event_type = 'search_performed'
       and profile_id is null
       and created_at > now() - interval '30 days'),
    (select count(distinct metadata ->> 'session') from events
      where profile_id is null
        and created_at > now() - interval '30 days');
end;
$fn$;

revoke execute on function admin_overview() from public, anon;
grant execute on function admin_overview() to authenticated;

-- ============================================================
-- Self-check
-- ============================================================
-- Shaped by what 0064 learned the hard way: a migration runs as the table
-- owner locally and as the CLI's login role against the live project, so a
-- check that switches roles or cleans up after itself with a DELETE is partly
-- testing whichever role it happens to be. The "an anonymous session really
-- can log an event" assertion therefore lives in visitor_events_test.sql,
-- which runs as postgres by design and rolls back.
--
-- What is left here is the half that cannot wait for CI. `log_visitor_event`
-- is a *new* function, so unlike a `create or replace` of an existing one it
-- does not inherit an owner -- it belongs to whoever pushed this migration,
-- and a SECURITY DEFINER function whose owner cannot write to `events` would
-- fail for every anonymous visitor while looking perfectly correct in the
-- diff. The only way to know is to make it write, here, against the database
-- being migrated. The block's implicit savepoint throws the row away again, so
-- nothing is left behind and no DELETE privilege is needed to do it.
do $chk$
declare
  v_wrote   boolean := false;
  v_refused boolean := false;
  v_why     text;
begin
  -- The table stays shut. If this ever passes, the function was a detour and
  -- the policy is what anyone will reach for instead.
  if has_table_privilege('anon', 'events', 'INSERT') then
    raise exception 'anon can insert events directly -- the throttle and the type whitelist are bypassed';
  end if;

  -- And the grant exists, which 0046 made a thing you have to say rather than
  -- something a new function gets for free.
  if not has_function_privilege('anon',
       'log_visitor_event(text,uuid,uuid,text,integer,boolean)', 'EXECUTE') then
    raise exception 'anon cannot execute log_visitor_event -- the signed-out funnel stays invisible';
  end if;

  begin
    perform log_visitor_event('search_performed', gen_random_uuid(), null, 'self-check', 0, false);
    v_wrote := true;
    -- Undo the row by failing out of the block.
    raise exception 'toolber-selfcheck-rollback';
  exception when others then
    v_why := sqlerrm;
    if v_why <> 'toolber-selfcheck-rollback' then
      raise exception 'log_visitor_event could not write as its own owner: %', v_why;
    end if;
  end;

  if not v_wrote then
    raise exception 'log_visitor_event self-check never ran';
  end if;

  -- The whitelist refuses before it writes, so this needs no savepoint.
  begin
    perform log_visitor_event('borrow_requested', gen_random_uuid());
  exception when others then
    v_refused := true;
    v_why := sqlerrm;
  end;

  if not v_refused then
    raise exception 'log_visitor_event accepted an event type outside the two public pages';
  end if;
  if v_why <> 'log_visitor_event does not accept borrow_requested' then
    raise exception 'log_visitor_event refused for the wrong reason: %', v_why;
  end if;
end;
$chk$;
